services:
  postgres:
    image: postgres:15-alpine
    container_name: geopulse_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup_postgres.sql:/docker-entrypoint-initdb.d/setup_postgres.sql
      - ./create_api_usage_table.sql:/docker-entrypoint-initdb.d/create_api_usage_table.sql
    networks:
      - geopulse_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: geopulse_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@geopulse.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - geopulse_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  geopulse_network:
    driver: bridge